name: musicme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spotify_sdk: ^1.0.1
  flutter_bloc: ^6.1.0
  cupertino_icons: ^1.0.0
  bloc: ^6.1.1
  equatable: ^1.2.3
  dartz: ^0.9.2
  mockito: 4.1.4
  http: ^0.12.2
  test:
  universal_io: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/MobileAppLayout.jpg
    - lib/features/music_app/data/local_data/input_log.json
    - lib/features/music_app/data/liked_songs.json
    - lib/features/music_app/data/track_query_params.json

  fonts:
    - family: Monotype-Corsiva
      fonts:
        - asset: assets/fonts/MTCORSVA.TTF
          style: italic
